
module Pod
  class Installer
    class UserProjectIntegrator
      # This class is responsible for integrating the library generated by a
      # {TargetDefinition} with its destination project.
      #
      class TargetIntegrator
        alias_method :mbox_add_copy_resources_script_phase_1028, :add_copy_resources_script_phase
        def add_copy_resources_script_phase
          mbox_add_copy_resources_script_phase_1028
          native_targets.each do |native_target|
            if native_target.static?
              TargetIntegrator.remove_copy_resources_script_phase_from_target(native_target)
            end
          end
        end
      end
    end
  end
end
